steps:
- name: gcr.io/moonrhythm-containers/golang:1.13.4-alpine3.10
  args: [go, build, -o, tirev, -ldflags, -w -s, -tags=cbrotli, main.go]
  env:
  - GOOS=linux
  - GOARCH=amd64
  - CGO_ENABLED=1
  - GOPROXY=https://proxy.golang.org
- name: gcr.io/cloud-builders/docker
  args: [build, -t, gcr.io/$PROJECT_ID/tirev, '.']
- name: gcr.io/cloud-builders/docker
  args: [tag, gcr.io/$PROJECT_ID/tirev, gcr.io/$PROJECT_ID/tirev:$TAG_NAME]

images:
- gcr.io/$PROJECT_ID/tirev
- gcr.io/$PROJECT_ID/tirev:$TAG_NAME
